# Generated by Django 3.0.3 on 2020-02-07 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('body', models.TextField(verbose_name='متن')),
                ('image_main', models.ImageField(blank=True, upload_to='photos/news/%Y%m%d', verbose_name='تصویر اصلی')),
                ('image_1', models.ImageField(blank=True, upload_to='photos/news/%Y%m%d', verbose_name='تصویر فرعی')),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'خبر',
                'verbose_name_plural': 'خبرها',
            },
        ),
    ]
