# Generated by Django 3.0.3 on 2020-02-07 20:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='عنوان')),
                ('sub_title', models.CharField(blank=True, max_length=50, verbose_name='زیر عنوان')),
                ('caption', models.TextField(verbose_name='توضیحات')),
                ('price', models.CharField(max_length=20, verbose_name='قیمت')),
                ('maintenance', models.IntegerField(default=100, verbose_name='موجودی محصول')),
                ('register_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='زمان ثبت کالا')),
                ('status', models.BooleanField(choices=[(1, 'موجود'), (0, 'ناموجود')], default=1, verbose_name='وضعیت محصول')),
                ('image_main', models.ImageField(blank=True, upload_to='photos/product/%Y%m%d', verbose_name='تصویر اصلی')),
                ('image_1', models.ImageField(blank=True, upload_to='photos/product/%Y%m%d', verbose_name='تصویر اول')),
                ('image_2', models.ImageField(blank=True, upload_to='photos/product/%Y%m%d', verbose_name='تصویر دوم')),
                ('image_3', models.ImageField(blank=True, upload_to='photos/product/%Y%m%d', verbose_name='تصویر سوم')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('how_many', models.IntegerField(default=1, verbose_name='تعداد ')),
                ('status', models.CharField(choices=[('Paid', 'پرداخت شد'), ('Not Paid', 'پرداخت نشده')], default='Not Paid', max_length=32, verbose_name='وضعیت پرداخت ')),
                ('receive_status', models.CharField(choices=[('NotReceived', 'تحویل نشده'), ('Received', 'تحویل شد')], default='NotReceived', max_length=32, verbose_name='وضعیت تحویل ')),
                ('total_price', models.IntegerField(blank=True, null=True, verbose_name='جمع کل ')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='خریدار ')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='product.Product', verbose_name='محصول مورد نظر ')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
            },
        ),
    ]
