# Generated by Django 3.0.3 on 2020-02-25 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offer',
            field=models.BooleanField(choices=[(1, 'دارد'), (0, 'ندارد')], default=0, verbose_name='تخفیف محصول'),
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(to='product.Product', verbose_name='محصولات سفارش شده'),
        ),
        migrations.AlterField(
            model_name='product',
            name='maintenance',
            field=models.IntegerField(default=1000, verbose_name='موجودی محصول'),
        ),
    ]
