# Generated by Django 3.0.3 on 2020-02-25 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.CharField(default='0', max_length=20, verbose_name='درصد تخقیف محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='offer',
            field=models.BooleanField(choices=[(0, 'ندارد'), (1, 'دارد')], default=0, verbose_name='تخفیف محصول'),
        ),
    ]
