# Generated by Django 3.0.3 on 2020-02-28 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0005_auto_20200225_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='receive_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='مشتری'),
        ),
        migrations.AlterField(
            model_name='order',
            name='how_many',
            field=models.CharField(blank=True, max_length=100, verbose_name='شماره رسید'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.BooleanField(choices=[(1, 'پرداخت شده'), (0, 'پرداخت نشده')], default=1, verbose_name='وضعیت پرداخت'),
        ),
    ]
