# Generated by Django 3.0.3 on 2020-02-28 18:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20200228_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='how_many',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(blank=True, verbose_name='آدرس'),
        ),
        migrations.AddField(
            model_name='order',
            name='bill_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='شماره رسید'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.BooleanField(default=False, verbose_name='وضعیت تحویل به پست'),
        ),
        migrations.AddField(
            model_name='order',
            name='details',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='order',
            name='post_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='کد رهگیری پست'),
        ),
        migrations.AddField(
            model_name='order',
            name='register_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='زمان ثبت کالا'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_cost',
            field=models.CharField(max_length=20, null=True, verbose_name='جمع سفارش'),
        ),
    ]
