# Generated by Django 3.0.3 on 2020-02-28 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20200228_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='products_ordered',
            field=models.TextField(blank=True, verbose_name='سفارشات مشتری'),
        ),
    ]
