# Generated by Django 3.0.3 on 2020-02-28 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_order_products_ordered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.BooleanField(choices=[(0, 'تحویل نشده'), (1, 'تحویل شده')], default=0, verbose_name='وضعیت تحویل به پست'),
        ),
    ]
