# Generated by Django 3.0.3 on 2020-03-04 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20200305_0028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='شرکت ارسال کننده')),
                ('cost', models.IntegerField(verbose_name='هزینه')),
            ],
            options={
                'verbose_name': 'ارسال کننده',
                'verbose_name_plural': 'ارسال کننده ها',
            },
        ),
    ]
