# Generated by Django 3.0.3 on 2020-03-04 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deliver_with',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Delivery', verbose_name='شرکت تحویل دهنده'),
        ),
        migrations.AlterField(
            model_name='order',
            name='post_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='کد رهگیری مرسوله'),
        ),
    ]
