# Generated by Django 3.0.3 on 2020-03-05 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20200305_0101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'verbose_name': 'شرکت ارسال کننده ', 'verbose_name_plural': 'شرکت های ارسال کننده '},
        ),
    ]
