# Generated by Django 3.0.3 on 2020-03-05 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_delivery_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='deliver_with',
        ),
        migrations.AddField(
            model_name='order',
            name='deliver_with',
            field=models.ManyToManyField(null=True, to='product.Delivery', verbose_name='شرکت تحویل دهنده'),
        ),
    ]
