# Generated by Django 3.0.3 on 2020-03-05 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_auto_20200305_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='deliver_with',
        ),
        migrations.AddField(
            model_name='order',
            name='deliver_with',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Delivery', verbose_name='شرکت تحویل دهنده'),
        ),
    ]
