# Generated by Django 3.0.3 on 2020-03-05 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_auto_20200305_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='cost',
            field=models.IntegerField(verbose_name='هزینه ارسال'),
        ),
    ]
